language: node_js
jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run typecheck
        - npm run test --coverage
      after_script: bash <(curl -s https://codecov.io/bash)
