version: "3.7"
services:
  tests:
    build: .
    command: ./build.sh --hello
    environment:
      - CODECOV_TOKEN
      - CHOKIDAR_USEPOLLING

  watch-acceptance:
    build:
      context: .
      target: base
    tty: true
    command: yarn test --watchAll
    environment:
      - TEST_MODE=acceptance
    volumes:
      - ./:/usr/src/app
