version: "3.7"
services:
  lint:
    build: .
    command: npm run lint

  typecheck:
    build: .
    command: npm run typecheck

  cover:
    build: .
    command: bash -c 'npm run cover && bash <(curl -s https://codecov.io/bash) -Z'

  release:
    build: .
    environment:
      - GITHUB_TOKEN
      - NPM_TOKEN
    command: npx semantic-release
